feat(channel): Add channel component
EC-USGS/pynhm pull request #80
Opened 2022-05-09 17:31 UTC by jdhughes-usgs

Channel functionality limited to calculating lateral inflow to segments. Required
refactoring of netcdf functionality so that data that is dimensioned by nsegments
can be written. Added metadata to csv functionality so netcdf output would use
metadata for variables, if available. Added a few helper functions to metadata class.

2022-05-16 17:01 UTC, jmccreight requested changes
overall, a real peach! actually not being cynical. this is a nice piece of coding to read and its clarity is helpful at showing potential improvements to the existing scheme.

2022-05-17 19:57 UTC, jmccreight commented on pynhm/base/meta.py
> +        numpy_type_str = int
might postpone

2022-05-17 20:05 UTC, jdhughes-usgs commented on pynhm/base/meta.py
> +    def find_variables(self, variables: varoptions) -> dict:
Added description to docstring - function ok

2022-05-17 20:07 UTC, jdhughes-usgs commented on pynhm/utils/netcdf_utils.py
> +            dimension_name = meta_dimensions(var_meta[var_name])
Consider further later.

2022-05-17 20:08 UTC, jdhughes-usgs commented on pynhm/utils/netcdf_utils.py
> +            hru_ids = coordinates["nhm_id"]
Table for now

2022-05-17 21:05 UTC, jdhughes-usgs commented on pynhm/hydrology/PRMSChannel.py
> +                * self.seg_depth ** (2.0 / 3.0)
that is correct.

2022-05-18 16:24 UTC, jdhughes-usgs commented on autotest/test_channel.py
> +        output_compare = {}
Moved what could be moved

2022-05-18 16:24 UTC, jdhughes-usgs commented on autotest/test_preprocess_csv.py
> +    _ = csv.nhm_seg
It exists

2022-05-18 16:24 UTC, jdhughes-usgs commented on pynhm/base/meta.py
> +        numpy_type_str = int
Leave for later

2022-05-18 16:25 UTC, jdhughes-usgs commented on pynhm/base/meta.py
> +
Done

2022-05-18 16:27 UTC, merged

2022-05-18 16:41 UTC, jdhughes-usgs commented on pynhm/hydrology/PRMSChannel.py
> +    Muskinggum routing function that calculates the upstream inflow and
No changes required. Assessment of what the muskingum_mann method does.

2022-05-18 16:42 UTC, jdhughes-usgs commented on pynhm/hydrology/PRMSChannel.py
> +                else:
No changes required. Assessment of what the muskingum_mann method does.

2022-05-18 16:42 UTC, jdhughes-usgs commented on pynhm/hydrology/PRMSChannel.py
> +            seg_current_inflow += seg_upstream_inflow[jseg]
No changes required. Assessment of what the muskingum_mann method does.

2022-05-18 16:44 UTC, jdhughes-usgs commented on pynhm/hydrology/PRMSChannel.py
> +
Added a summary of the method.

2022-05-18 16:44 UTC, jdhughes-usgs commented on pynhm/hydrology/PRMSChannel.py
> +        Kcoef = np.where(self.segment_type == SegmentType.LAKE, 24.0, Kcoef)
Modified

2022-05-18 16:46 UTC, jdhughes-usgs commented on pynhm/hydrology/PRMSChannel.py
> +        self.seg_outflow = self.segment_flow_init
Moved

2022-05-18 16:46 UTC, jdhughes-usgs commented on pynhm/hydrology/PRMSChannel.py
> +        # todo: vectorize this
No changes required. Assessment of what the muskingum_mann method does.

2022-05-18 16:46 UTC, jdhughes-usgs commented on test_data/scripts/test_nc_domains.py
> +import numpy as np
Revised imports